// <auto-generated />
using System;
using JobPortal.Catalog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPortal.Catalog.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240101000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("JobPortal.Catalog.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("int");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc).AddMonths(-12),
                            Description = "Leading software development company",
                            EmployeeCount = 500,
                            Industry = "Information Technology",
                            Name = "TechCorp Solutions",
                            Website = "https://techcorp.example.com"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc).AddMonths(-8),
                            Description = "Data science and analytics consulting",
                            EmployeeCount = 150,
                            Industry = "Consulting",
                            Name = "DataMinds Inc",
                            Website = "https://dataminds.example.com"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc).AddMonths(-6),
                            Description = "Cloud infrastructure and DevOps services",
                            EmployeeCount = 300,
                            Industry = "Cloud Services",
                            Name = "CloudNative Systems",
                            Website = "https://cloudnative.example.com"
                        });
                });

            modelBuilder.Entity("JobPortal.Catalog.Domain.Entities.CompanyContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("company_contacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Tech Street",
                            City = "Kyiv",
                            CompanyId = 1,
                            Country = "Ukraine",
                            Email = "hr@techcorp.example.com",
                            Phone = "+380441234567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Data Avenue",
                            City = "Lviv",
                            CompanyId = 2,
                            Country = "Ukraine",
                            Email = "careers@dataminds.example.com",
                            Phone = "+380442345678"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Cloud Boulevard",
                            City = "Kharkiv",
                            CompanyId = 3,
                            Country = "Ukraine",
                            Email = "jobs@cloudnative.example.com",
                            Phone = "+380443456789"
                        });
                });

            modelBuilder.Entity("JobPortal.Catalog.Domain.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("SalaryMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalaryMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("IsActive");

                    b.HasIndex("PostedAt");

                    b.ToTable("jobs", t =>
                        {
                            t.HasCheckConstraint("CK_Jobs_Salary", "salary_max >= salary_min");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "We are looking for an experienced .NET developer to join our team.",
                            EmploymentType = "Full-time",
                            ExperienceYears = 5,
                            IsActive = true,
                            Location = "Kyiv, Ukraine",
                            PostedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc).AddDays(-10),
                            SalaryMax = 5000m,
                            SalaryMin = 3000m,
                            Title = "Senior .NET Developer"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CompanyId = 2,
                            Description = "Join our data science team to build ML models.",
                            EmploymentType = "Full-time",
                            ExperienceYears = 3,
                            IsActive = true,
                            Location = "Lviv, Ukraine",
                            PostedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc).AddDays(-7),
                            SalaryMax = 4500m,
                            SalaryMin = 2500m,
                            Title = "Data Scientist"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CompanyId = 3,
                            Description = "Looking for a DevOps engineer with Kubernetes experience.",
                            EmploymentType = "Full-time",
                            ExperienceYears = 4,
                            IsActive = true,
                            Location = "Kharkiv, Ukraine",
                            PostedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc).AddDays(-5),
                            SalaryMax = 4800m,
                            SalaryMin = 2800m,
                            Title = "DevOps Engineer"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "Frontend developer position with React expertise.",
                            EmploymentType = "Full-time",
                            ExperienceYears = 2,
                            IsActive = true,
                            Location = "Remote",
                            PostedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc).AddDays(-3),
                            SalaryMax = 3500m,
                            SalaryMin = 2000m,
                            Title = "React Developer"
                        });
                });

            modelBuilder.Entity("JobPortal.Catalog.Domain.Entities.JobCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("job_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Software engineering and development roles",
                            Name = "Software Development"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Data analysis and machine learning roles",
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 3,
                            Description = "DevOps and infrastructure roles",
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = 4,
                            Description = "UI/UX and graphic design roles",
                            Name = "Design"
                        });
                });

            modelBuilder.Entity("JobPortal.Catalog.Domain.Entities.JobSkillRequirement", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("SkillTagId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RequiredLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("JobId", "SkillTagId");

                    b.HasIndex("SkillTagId");

                    b.ToTable("job_skill_requirements", (string)null);

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            SkillTagId = 1,
                            IsRequired = true,
                            RequiredLevel = "Expert"
                        },
                        new
                        {
                            JobId = 1,
                            SkillTagId = 2,
                            IsRequired = true,
                            RequiredLevel = "Expert"
                        },
                        new
                        {
                            JobId = 1,
                            SkillTagId = 6,
                            IsRequired = true,
                            RequiredLevel = "Advanced"
                        },
                        new
                        {
                            JobId = 2,
                            SkillTagId = 3,
                            IsRequired = true,
                            RequiredLevel = "Expert"
                        },
                        new
                        {
                            JobId = 2,
                            SkillTagId = 6,
                            IsRequired = true,
                            RequiredLevel = "Advanced"
                        },
                        new
                        {
                            JobId = 3,
                            SkillTagId = 7,
                            IsRequired = true,
                            RequiredLevel = "Expert"
                        },
                        new
                        {
                            JobId = 3,
                            SkillTagId = 8,
                            IsRequired = true,
                            RequiredLevel = "Advanced"
                        },
                        new
                        {
                            JobId = 4,
                            SkillTagId = 4,
                            IsRequired = true,
                            RequiredLevel = "Expert"
                        },
                        new
                        {
                            JobId = 4,
                            SkillTagId = 5,
                            IsRequired = true,
                            RequiredLevel = "Expert"
                        });
                });

            modelBuilder.Entity("JobPortal.Catalog.Domain.Entities.SkillTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("skill_tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Programming Language",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Framework",
                            Name = ".NET"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Programming Language",
                            Name = "Python"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Programming Language",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Framework",
                            Name = "React"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Database",
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 7,
                            Category = "DevOps",
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 8,
                            Category = "DevOps",
                            Name = "Kubernetes"
                        });
                });

            modelBuilder.Entity("JobPortal.Catalog.Domain.Entities.CompanyContact", b =>
                {
                    b.HasOne("JobPortal.Catalog.Domain.Entities.Company", "Company")
                        .WithOne("Contact")
                        .HasForeignKey("JobPortal.Catalog.Domain.Entities.CompanyContact", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("JobPortal.Catalog.Domain.Entities.Job", b =>
                {
                    b.HasOne("JobPortal.Catalog.Domain.Entities.JobCategory", "Category")
                        .WithMany("Jobs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPortal.Catalog.Domain.Entities.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("JobPortal.Catalog.Domain.Entities.JobSkillRequirement", b =>
                {
                    b.HasOne("JobPortal.Catalog.Domain.Entities.Job", "Job")
                        .WithMany("SkillRequirements")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Catalog.Domain.Entities.SkillTag", "SkillTag")
                        .WithMany("JobSkillRequirements")
                        .HasForeignKey("SkillTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("SkillTag");
                });

            modelBuilder.Entity("JobPortal.Catalog.Domain.Entities.Company", b =>
                {
                    b.Navigation("Contact");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("JobPortal.Catalog.Domain.Entities.Job", b =>
                {
                    b.Navigation("SkillRequirements");
                });

            modelBuilder.Entity("JobPortal.Catalog.Domain.Entities.JobCategory", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("JobPortal.Catalog.Domain.Entities.SkillTag", b =>
                {
                    b.Navigation("JobSkillRequirements");
                });
#pragma warning restore 612, 618
        }
    }
}
